# Generated by Django 4.2.7 on 2023-12-01 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0004_user_is_staff_alter_user_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Psikiater",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("kualifikasi", models.BooleanField(default=False)),
                ("ulasanKonsultasi", models.TextField(default="")),
                ("jadwalKonsultasi", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("authentication.user",),
        ),
    ]
