# Generated by Django 4.2.7 on 2023-12-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psikiater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalKonsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psikiater', models.CharField(max_length=255)),
                ('tanggal', models.DateTimeField()),
                ('ketersediaan', models.BooleanField(default=True)),
            ],
        ),
    ]
