# Generated by Django 5.0 on 2023-12-11 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psikiater', '0002_jadwalkonsultasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwalkonsultasi',
            old_name='tanggal',
            new_name='tanggal_ketersediaan',
        ),
        migrations.AlterField(
            model_name='jadwalkonsultasi',
            name='psikiater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psikiater.psikiater'),
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('metode', models.CharField(max_length=255)),
                ('keterangan', models.CharField(max_length=255)),
                ('kuota_total', models.IntegerField()),
                ('kuota_tersedia', models.IntegerField()),
                ('psikiater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
