# Generated by Django 5.0 on 2023-12-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psikiater', '0003_rename_tanggal_jadwalkonsultasi_tanggal_ketersediaan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwalkonsultasi',
            old_name='tanggal_ketersediaan',
            new_name='jadwal_konsultasi',
        ),
        migrations.RemoveField(
            model_name='jadwalkonsultasi',
            name='ketersediaan',
        ),
    ]
