# Generated by Django 4.2.7 on 2023-12-01 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("psikiater", "0001_initial"),
        ("authentication", "0004_user_is_staff_alter_user_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pasien",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("authentication.user",),
        ),
        migrations.CreateModel(
            name="Ulasan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("komentar", models.TextField()),
                ("rating", models.FloatField()),
                ("tanggalKonsultasi", models.DateTimeField(auto_now_add=True)),
                ("namaPsikiater", models.CharField(max_length=100)),
                (
                    "pasien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pasien.pasien"
                    ),
                ),
                (
                    "psikiater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psikiater.psikiater",
                    ),
                ),
            ],
        ),
    ]
