# Generated by Django 4.2.7 on 2023-12-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psikiater', '0003_rename_jam_jadwal_jam_mulai_and_more'),
        ('pasien', '0002_ulasan_chage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesananKonsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasien', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('bayar', 'Menunggu Pembayaran'), ('verify', 'Menunggu Verifikasi Admin'), ('pending', 'Menunggu Konfirmasi Psikiater'), ('scheduled', 'Konsultasi Terjadwal'), ('done', 'Selesai')], default='bayar', max_length=9)),
                ('jadwal_konsultasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psikiater.jadwal')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biayaPembayaran', models.FloatField()),
                ('metodePembayaran', models.CharField(choices=[('ots', 'Bayar di tempat'), ('card', 'Kartu Kredit/Kartu Debit'), ('va', 'Virtual Account'), ('ewallet', 'E-Wallet'), ('retail', 'Gerai Retail')], max_length=7)),
                ('buktiPembayaran', models.ImageField(upload_to='images')),
                ('statusPembayaran', models.BooleanField(default=False)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasien.pesanankonsultasi')),
            ],
        ),
    ]
