# Generated by Django 4.2.7 on 2023-12-11 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasien', '0003_pesanankonsultasi_pembayaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasien',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='pasien',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
