# Generated by Django 4.2.7 on 2023-12-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0005_alter_pesanankonsultasi_pasien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='biayaPembayaran',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='buktiPembayaran',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='byte_image',
            field=models.TextField(blank=True),
        ),
    ]
