# Generated by Django 4.2.7 on 2023-12-12 06:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0006_remove_pembayaran_biayapembayaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulasan',
            name='pesanan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pasien.pesanankonsultasi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pesanankonsultasi',
            name='status',
            field=models.CharField(choices=[('bayar', 'Menunggu Pembayaran'), ('verify', 'Menunggu Verifikasi Admin'), ('scheduled', 'Konsultasi Terjadwal'), ('done', 'Selesai')], default='bayar', max_length=9),
        ),
    ]
